# Generated by Django 2.2.3 on 2020-01-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerymeals_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='formatted_title',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
