# Generated by Django 2.2.3 on 2020-01-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerymeals_app', '0002_product_formatted_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.CharField(default='Sprouts', max_length=50),
            preserve_default=False,
        ),
    ]
