# Generated by Django 2.2.3 on 2020-01-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerymeals_app', '0004_shoppinglistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
