# Generated by Django 2.2.3 on 2020-01-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerymeals_app', '0007_auto_20200111_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_link',
            field=models.CharField(default='none', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=10000),
        ),
    ]
