# Generated by Django 2.2.3 on 2020-01-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocerymeals_app', '0009_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
    ]
